name: bookingmanager
description: Booking Manager.

publish_to: "none"
version: 2.0.10+18

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.4
  easy_localization: ^3.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  syncfusion_flutter_calendar: ^22.2.5
  syncfusion_localizations: ^22.2.5
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^22.2.8
  cached_network_image: ^3.2.3
  firebase_storage: ^11.2.6
  image_picker: ^1.0.2
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.1
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
